create_project finn_vivado_stitch_proj /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso -part xc7z020clg400-1
set_property ip_repo_paths [list /workspace/finn/finn-rtllib/memstream /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_0_l4ym_9_8/project_StreamingDataflowPartition_1_StreamingFIFO_0/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_Thresholding_Batch_0_vjkgt09l/project_Thresholding_Batch_0/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_ConvolutionInputGenerator_0_6_q6vi1l/project_ConvolutionInputGenerator_0/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_2_ntydo62u/project_StreamingFIFO_2/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_0_xhr36c17/project_StreamingFCLayer_Batch_0/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_3_ell2234z/project_StreamingFIFO_3/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_ConvolutionInputGenerator_1_adgu7igh/project_ConvolutionInputGenerator_1/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_4_d1hhjmyu/project_StreamingFIFO_4/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_1_zime8ynw/project_StreamingFCLayer_Batch_1/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_0_m8evnhbv/project_StreamingDataWidthConverter_Batch_0/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingMaxPool_Batch_0_2mua8oeo/project_StreamingMaxPool_Batch_0/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_7_dwzm2obq/project_StreamingFIFO_7/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_1_fqls_jx6/project_StreamingDataWidthConverter_Batch_1/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_8_4n56s9pc/project_StreamingFIFO_8/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_ConvolutionInputGenerator_2_2ypl2foj/project_ConvolutionInputGenerator_2/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_9_9lytyivo/project_StreamingFIFO_9/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_2_sa05cpbz/project_StreamingFCLayer_Batch_2/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_2_0sfp1vf5/project_StreamingDataWidthConverter_Batch_2/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_ConvolutionInputGenerator_3_cf2t2sy9/project_ConvolutionInputGenerator_3/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_12_pnrsmp15/project_StreamingFIFO_12/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_3_6w_3jl5s/project_StreamingFCLayer_Batch_3/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_3_lq8nxzkz/project_StreamingDataWidthConverter_Batch_3/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingMaxPool_Batch_1_hssgkqph/project_StreamingMaxPool_Batch_1/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_4_nrbged9g/project_StreamingDataWidthConverter_Batch_4/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_ConvolutionInputGenerator_4_e9ds8j3w/project_ConvolutionInputGenerator_4/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFIFO_17_6l6kfvzz/project_StreamingFIFO_17/sol1/impl/verilog /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_4_x1xz72eu/project_StreamingFCLayer_Batch_4/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_5_yezbpo0i/project_StreamingDataWidthConverter_Batch_5/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_ConvolutionInputGenerator_5_q2ola4w4/project_ConvolutionInputGenerator_5/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_5_ou4xx96e/project_StreamingFCLayer_Batch_5/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_6_ys1q5ebr/project_StreamingDataWidthConverter_Batch_6/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_6_rbv8qzhw/project_StreamingFCLayer_Batch_6/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_7_am9l07ix/project_StreamingDataWidthConverter_Batch_7/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_7_mpax47i8/project_StreamingFCLayer_Batch_7/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_8_6h19e7wo/project_StreamingDataWidthConverter_Batch_8/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_8_y6xa8r5s/project_StreamingFCLayer_Batch_8/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataWidthConverter_Batch_9_dobn1jm2/project_StreamingDataWidthConverter_Batch_9/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_LabelSelect_Batch_0_oj00bw3k/project_LabelSelect_Batch_0/sol1/impl/ip /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingDataflowPartition_1_StreamingFIFO_9_5e6pvg0e/project_StreamingDataflowPartition_1_StreamingFIFO_9/sol1/impl/verilog] [current_project]
update_ip_catalog
create_bd_design "StreamingDataflowPartition_1"
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_0:1.0 StreamingDataflowPartition_1_StreamingFIFO_0
create_bd_cell -type ip -vlnv xilinx.com:hls:Thresholding_Batch_0:1.0 StreamingDataflowPartition_1_Thresholding_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_0:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_0
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFIFO_1
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFIFO_1/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFIFO_1/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_1/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_1/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingDataflowPartition_1_StreamingFIFO_1/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {1024}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_1/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_1/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_1/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/fifo/M_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/out_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/fifo/S_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/in0_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_0
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_0:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {864} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_0_xhr36c17/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {864} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V]
save_bd_design
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFIFO_2
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFIFO_2/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFIFO_2/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_2/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_2/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingDataflowPartition_1_StreamingFIFO_2/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {4096}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_2/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_2/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_2/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/fifo/M_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/out_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/fifo/S_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/in0_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/fifo/s_axis_aclk]
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_1:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_1
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFIFO_3
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFIFO_3/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFIFO_3/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_3/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_3/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingDataflowPartition_1_StreamingFIFO_3/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {8192}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_3/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_3/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_3/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/fifo/M_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/out_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/fifo/S_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/in0_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_1
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_1:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {9216} CONFIG.MEM_WIDTH {16} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_1_zime8ynw/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {9216} CONFIG.STRM0_WIDTH {16} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_0:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_0:1.0 StreamingDataflowPartition_1_StreamingMaxPool_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_7:1.0 StreamingDataflowPartition_1_StreamingFIFO_4
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_1:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFIFO_8:1.0 StreamingDataflowPartition_1_StreamingFIFO_5
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_2:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_2
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFIFO_6
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFIFO_6/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFIFO_6/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_6/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_6/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingDataflowPartition_1_StreamingFIFO_6/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {4096}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_6/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_6/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {1}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_6/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/fifo/M_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/out_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/fifo/S_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/in0_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_2
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_2:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {18432} CONFIG.MEM_WIDTH {16} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_2_sa05cpbz/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {18432} CONFIG.STRM0_WIDTH {16} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_2:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_3:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_3
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFIFO_7
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFIFO_7/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFIFO_7/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_7/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_7/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingDataflowPartition_1_StreamingFIFO_7/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {4096}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_7/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_7/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {2}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_7/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/fifo/M_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/out_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/fifo/S_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/in0_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_3
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_3:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {18432} CONFIG.MEM_WIDTH {32} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_3_6w_3jl5s/} CONFIG.RAM_STYLE {block} CONFIG.STRM0_DEPTH {18432} CONFIG.STRM0_WIDTH {32} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_3:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingMaxPool_Batch_1:1.0 StreamingDataflowPartition_1_StreamingMaxPool_Batch_1
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_4:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_4:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_4
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFIFO_8
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFIFO_8/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFIFO_8/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_8/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFIFO_8/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 /StreamingDataflowPartition_1_StreamingFIFO_8/fifo
set_property -dict [list CONFIG.FIFO_DEPTH {1024}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_8/fifo]
set_property -dict [list CONFIG.FIFO_MEMORY_TYPE {auto}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_8/fifo]
set_property -dict [list CONFIG.TDATA_NUM_BYTES {2}] [get_bd_cells /StreamingDataflowPartition_1_StreamingFIFO_8/fifo]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/fifo/M_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/out_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/fifo/S_AXIS] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/in0_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/fifo/s_axis_aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/fifo/s_axis_aclk]
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_4
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_4:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {36864} CONFIG.MEM_WIDTH {32} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_4_x1xz72eu/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {36864} CONFIG.STRM0_WIDTH {32} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_5:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:hls:ConvolutionInputGenerator_5:1.0 StreamingDataflowPartition_1_ConvolutionInputGenerator_5
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_5
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_5:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {147456} CONFIG.MEM_WIDTH {16} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_5_ou4xx96e/} CONFIG.RAM_STYLE {auto} CONFIG.STRM0_DEPTH {147456} CONFIG.STRM0_WIDTH {16} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_6:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_6
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_6:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {65536} CONFIG.MEM_WIDTH {8} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_6_rbv8qzhw/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {65536} CONFIG.STRM0_WIDTH {8} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_7:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_7
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_7:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {65536} CONFIG.MEM_WIDTH {16} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_7_mpax47i8/} CONFIG.RAM_STYLE {block} CONFIG.STRM0_DEPTH {65536} CONFIG.STRM0_WIDTH {16} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_8:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8
create_bd_cell -type hier StreamingDataflowPartition_1_StreamingFCLayer_Batch_8
create_bd_pin -dir I -type clk /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk
create_bd_pin -dir I -type rst /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n
create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V
create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingFCLayer_Batch_8:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8
create_bd_cell -type ip -vlnv xilinx.com:user:memstream:1.0 /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm
set_property -dict [list CONFIG.NSTREAMS {1} CONFIG.MEM_DEPTH {512} CONFIG.MEM_WIDTH {32} CONFIG.MEM_INIT {/home/grgov/Diplomski_rad/finn_modified_docker_output_dir/code_gen_ipgen_StreamingFCLayer_Batch_8_y6xa8r5s/} CONFIG.RAM_STYLE {distributed} CONFIG.STRM0_DEPTH {512} CONFIG.STRM0_WIDTH {32} CONFIG.STRM0_OFFSET {0} ] [get_bd_cells /StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm/m_axis_0] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/weights_V_V]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm/aresetn]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8_wstrm/aclk]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n]
connect_bd_net [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V]
save_bd_design
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataWidthConverter_Batch_9:1.0 StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_9
create_bd_cell -type ip -vlnv xilinx.com:hls:LabelSelect_Batch_0:1.0 StreamingDataflowPartition_1_LabelSelect_Batch_0
create_bd_cell -type ip -vlnv xilinx.com:hls:StreamingDataflowPartition_1_StreamingFIFO_9:1.0 StreamingDataflowPartition_1_StreamingFIFO_9
make_bd_pins_external [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_0/ap_clk]
set_property name ap_clk [get_bd_ports ap_clk_0]
make_bd_pins_external [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_0/ap_rst_n]
set_property name ap_rst_n [get_bd_ports ap_rst_n_0]
make_bd_intf_pins_external [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_0/in0_V_V]
set_property name s_axis_0 [get_bd_intf_ports in0_V_V_0]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_Thresholding_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_Thresholding_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_Thresholding_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_Thresholding_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_2/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_3/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingMaxPool_Batch_1/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_4/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_ConvolutionInputGenerator_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_5/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_6/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_7/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_9/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFCLayer_Batch_8/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_9/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_StreamingDataWidthConverter_Batch_9/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/in0_V_V]
connect_bd_net [get_bd_ports ap_rst_n] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_9/ap_rst_n]
connect_bd_net [get_bd_ports ap_clk] [get_bd_pins StreamingDataflowPartition_1_StreamingFIFO_9/ap_clk]
connect_bd_intf_net [get_bd_intf_pins StreamingDataflowPartition_1_LabelSelect_Batch_0/out_V_V] [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_9/in0_V_V]
make_bd_intf_pins_external [get_bd_intf_pins StreamingDataflowPartition_1_StreamingFIFO_9/out_V_V]
set_property name m_axis_0 [get_bd_intf_ports out_V_V_0]
set_property CONFIG.FREQ_HZ 100000000.000000 [get_bd_ports /ap_clk]
regenerate_bd_layout
validate_bd_design
save_bd_design
make_wrapper -files [get_files /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/StreamingDataflowPartition_1.bd] -top
add_files -norecurse /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/hdl/StreamingDataflowPartition_1_wrapper.v
set_property SYNTH_CHECKPOINT_MODE Hierarchical [ get_files /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_1/StreamingDataflowPartition_1.bd ]
set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value {-mode out_of_context} -objects [get_runs synth_1]
launch_runs synth_1 -jobs 6
wait_on_run [get_runs synth_1]
open_run synth_1 -name synth_1
write_verilog -force -mode synth_stub StreamingDataflowPartition_1.v
write_checkpoint StreamingDataflowPartition_1.dcp
write_xdc StreamingDataflowPartition_1.xdc
report_utilization -file StreamingDataflowPartition_1_partition_util.rpt
ipx::package_project -root_dir /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip -vendor xilinx_finn -library finn -taxonomy /UserIP -module StreamingDataflowPartition_1 -import_files
set_property core_revision 2 [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::create_xgui_files [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::remove_bus_parameter FREQ_HZ [ipx::get_bus_interfaces CLK.AP_CLK -of_objects [ipx::current_core]]
set_property sdx_kernel true [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set_property sdx_kernel_type rtl [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set_property supported_families { } [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set_property xpm_libraries {XPM_CDC XPM_MEMORY XPM_FIFO} [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set_property auto_family_support_level level_2 [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::remove_all_file [ipx::get_file_groups xilinx_anylanguagebehavioralsimulation]
ipx::remove_all_file [ipx::get_file_groups xilinx_anylanguagesynthesis]
ipx::remove_file_group xilinx_anylanguagebehavioralsimulation [ipx::current_core]
ipx::remove_file_group xilinx_anylanguagesynthesis [ipx::current_core]
file delete -force /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip/sim
file delete -force /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip/src
file mkdir /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip/dcp
file mkdir /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip/impl
file copy -force StreamingDataflowPartition_1.dcp /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip/dcp
file copy -force StreamingDataflowPartition_1.xdc /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/ip/impl
ipx::add_file_group xilinx_implementation [ipx::current_core]
ipx::add_file impl/StreamingDataflowPartition_1.xdc [ipx::get_file_groups xilinx_implementation]
set_property used_in [list implementation] [ipx::get_files impl/StreamingDataflowPartition_1.xdc -of_objects [ipx::get_file_groups xilinx_implementation]]
ipx::add_file_group xilinx_synthesischeckpoint [ipx::current_core]
ipx::add_file dcp/StreamingDataflowPartition_1.dcp [ipx::get_file_groups xilinx_synthesischeckpoint]
ipx::add_file_group xilinx_simulationcheckpoint [ipx::current_core]
ipx::add_file dcp/StreamingDataflowPartition_1.dcp [ipx::get_file_groups xilinx_simulationcheckpoint]
ipx::update_checksums [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
ipx::save_core [ipx::find_open_core xilinx_finn:finn:StreamingDataflowPartition_1:1.0]
set all_v_files [get_files -filter {FILE_TYPE == Verilog && USED_IN_SYNTHESIS == 1} ]
set fp [open /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj_k865pjso/all_verilog_srcs.txt w]
foreach vf $all_v_files {puts $fp $vf}
close $fp
