// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGenerator_0_ConvolutionInputGene_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [7:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln196_fu_376_p2;
wire   [0:0] icmp_ln198_fu_398_p2;
wire   [0:0] and_ln244_fu_606_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln198_reg_900;
reg   [0:0] icmp_ln198_reg_900_pp0_iter1_reg;
reg   [0:0] icmp_ln214_reg_904;
reg   [0:0] icmp_ln214_reg_904_pp0_iter1_reg;
reg   [14:0] i_0_0_reg_279;
reg    ap_predicate_op111_read_state2;
reg    ap_predicate_op154_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_predicate_op206_write_state4;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [14:0] add_ln196_fu_382_p2;
wire   [0:0] icmp_ln214_fu_407_p2;
wire   [31:0] add_ln219_1_fu_457_p2;
reg   [31:0] add_ln219_1_reg_908;
wire   [1:0] add_ln220_fu_469_p2;
reg   [1:0] add_ln220_reg_913;
reg   [1:0] add_ln220_reg_913_pp0_iter1_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire   [6:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [7:0] inputBuf_0_V_q0;
reg   [6:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
wire   [6:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [7:0] inputBuf_1_V_q0;
reg   [6:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
wire   [6:0] inputBuf_2_V_address0;
reg    inputBuf_2_V_ce0;
wire   [7:0] inputBuf_2_V_q0;
reg   [6:0] inputBuf_2_V_address1;
reg    inputBuf_2_V_ce1;
reg    inputBuf_2_V_we1;
wire   [6:0] inputBuf_3_V_address0;
reg    inputBuf_3_V_ce0;
wire   [7:0] inputBuf_3_V_q0;
reg   [6:0] inputBuf_3_V_address1;
reg    inputBuf_3_V_ce1;
reg    inputBuf_3_V_we1;
wire   [63:0] zext_ln247_fu_612_p1;
wire   [63:0] zext_ln201_fu_724_p1;
wire   [63:0] zext_ln220_fu_788_p1;
reg   [31:0] ofm_y_1_0_fu_86;
wire   [31:0] select_ln235_1_fu_563_p3;
wire   [0:0] icmp_ln223_fu_481_p2;
wire   [0:0] icmp_ln226_fu_498_p2;
wire   [0:0] icmp_ln229_fu_509_p2;
wire   [0:0] icmp_ln232_fu_529_p2;
reg   [31:0] ofm_x_1_0_fu_90;
wire   [31:0] add_ln231_fu_523_p2;
reg   [31:0] k_y_1_0_fu_94;
wire   [31:0] add_ln215_fu_429_p2;
reg   [31:0] inp_15_0_fu_98;
wire   [31:0] select_ln235_fu_555_p3;
wire   [31:0] add_ln203_fu_736_p2;
reg   [31:0] k_x_1_0_fu_102;
wire   [31:0] add_ln225_fu_492_p2;
reg   [31:0] count_simd_1_0_fu_106;
wire   [31:0] add_ln222_fu_475_p2;
reg   [31:0] read_block_1_0_fu_110;
wire   [31:0] zext_ln251_fu_677_p1;
wire   [31:0] add_ln210_fu_772_p2;
wire   [0:0] icmp_ln204_fu_350_p2;
reg   [31:0] current_block_write_s_fu_114;
wire   [31:0] select_ln251_fu_653_p3;
wire   [31:0] select_ln207_fu_764_p3;
reg   [31:0] current_line_1_0_fu_118;
wire   [31:0] select_ln251_1_fu_661_p3;
wire   [31:0] grp_fu_338_p2;
reg   [31:0] counter_internal_blo_fu_122;
wire   [31:0] select_ln263_fu_711_p3;
wire   [7:0] tmp_V_1_fu_795_p6;
reg    ap_block_pp0_stage0_01001;
wire   [1:0] trunc_ln321_1_fu_620_p1;
wire   [1:0] trunc_ln321_fu_732_p1;
wire   [31:0] add_ln219_fu_439_p2;
wire   [31:0] shl_ln219_fu_445_p2;
wire   [31:0] sub_ln219_fu_451_p2;
wire   [1:0] trunc_ln215_1_fu_435_p1;
wire   [1:0] add_ln220_1_fu_463_p2;
wire   [1:0] trunc_ln215_fu_425_p1;
wire   [31:0] add_ln234_fu_543_p2;
wire   [0:0] icmp_ln235_fu_549_p2;
wire   [26:0] tmp_1_fu_590_p4;
wire   [0:0] icmp_ln244_fu_584_p2;
wire   [0:0] icmp_ln244_1_fu_600_p2;
wire   [5:0] trunc_ln196_fu_394_p1;
wire   [31:0] add_ln255_fu_633_p2;
wire   [0:0] icmp_ln256_fu_639_p2;
wire   [0:0] icmp_ln251_fu_344_p2;
wire   [31:0] select_ln256_fu_645_p3;
wire   [5:0] add_ln255_1_fu_627_p2;
wire   [5:0] select_ln251_2_fu_669_p3;
wire   [31:0] add_ln262_fu_699_p2;
wire   [0:0] icmp_ln263_fu_705_p2;
wire   [31:0] add_ln206_fu_752_p2;
wire   [0:0] icmp_ln207_fu_758_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op119_store_state2;
reg    ap_enable_operation_119;
reg    ap_enable_state2_pp0_iter0_stage0;
reg    ap_predicate_op162_store_state2;
reg    ap_enable_operation_162;
reg    ap_predicate_op198_load_state3;
reg    ap_enable_operation_198;
reg    ap_enable_state3_pp0_iter1_stage0;
reg    ap_predicate_op203_load_state4;
reg    ap_enable_operation_203;
reg    ap_enable_state4_pp0_iter2_stage0;
reg    ap_predicate_op121_store_state2;
reg    ap_enable_operation_121;
reg    ap_predicate_op164_store_state2;
reg    ap_enable_operation_164;
reg    ap_predicate_op196_load_state3;
reg    ap_enable_operation_196;
reg    ap_predicate_op202_load_state4;
reg    ap_enable_operation_202;
reg    ap_predicate_op123_store_state2;
reg    ap_enable_operation_123;
reg    ap_predicate_op166_store_state2;
reg    ap_enable_operation_166;
reg    ap_predicate_op194_load_state3;
reg    ap_enable_operation_194;
reg    ap_predicate_op201_load_state4;
reg    ap_enable_operation_201;
reg    ap_predicate_op125_store_state2;
reg    ap_enable_operation_125;
reg    ap_predicate_op168_store_state2;
reg    ap_enable_operation_168;
reg    ap_predicate_op200_load_state3;
reg    ap_enable_operation_200;
reg    ap_predicate_op204_load_state4;
reg    ap_enable_operation_204;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_694;
reg    ap_condition_249;
reg    ap_condition_700;
reg    ap_condition_704;
reg    ap_condition_708;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

ConvolutionInputGenerator_0_ConvolutionInputGbkb #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(in_V_V_TDATA)
);

ConvolutionInputGenerator_0_ConvolutionInputGbkb #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(in_V_V_TDATA)
);

ConvolutionInputGenerator_0_ConvolutionInputGbkb #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
inputBuf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_V_address0),
    .ce0(inputBuf_2_V_ce0),
    .q0(inputBuf_2_V_q0),
    .address1(inputBuf_2_V_address1),
    .ce1(inputBuf_2_V_ce1),
    .we1(inputBuf_2_V_we1),
    .d1(in_V_V_TDATA)
);

ConvolutionInputGenerator_0_ConvolutionInputGbkb #(
    .DataWidth( 8 ),
    .AddressRange( 96 ),
    .AddressWidth( 7 ))
inputBuf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_V_address0),
    .ce0(inputBuf_3_V_ce0),
    .q0(inputBuf_3_V_q0),
    .address1(inputBuf_3_V_address1),
    .ce1(inputBuf_3_V_ce1),
    .we1(inputBuf_3_V_we1),
    .d1(in_V_V_TDATA)
);

ConvolutionInputGenerator_0_ConvolutionInputGfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
ConvolutionInputGfYi_U1(
    .din0(inputBuf_0_V_q0),
    .din1(inputBuf_1_V_q0),
    .din2(inputBuf_2_V_q0),
    .din3(inputBuf_3_V_q0),
    .din4(add_ln220_reg_913_pp0_iter1_reg),
    .dout(tmp_V_1_fu_795_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln223_fu_481_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        count_simd_1_0_fu_106 <= add_ln222_fu_475_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln226_fu_498_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln229_fu_509_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln232_fu_529_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln232_fu_529_p2 == 1'd1) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_1_0_fu_106 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counter_internal_blo_fu_122 <= select_ln263_fu_711_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln204_fu_350_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_122 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln204_fu_350_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_s_fu_114 <= select_ln207_fu_764_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_s_fu_114 <= select_ln251_fu_653_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_s_fu_114 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln204_fu_350_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_line_1_0_fu_118 <= grp_fu_338_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_line_1_0_fu_118 <= select_ln251_1_fu_661_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln204_fu_350_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_1_0_fu_118 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_0_reg_279 <= 15'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_0_reg_279 <= add_ln196_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_15_0_fu_98 <= add_ln203_fu_736_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln232_fu_529_p2 == 1'd1) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_15_0_fu_98 <= select_ln235_fu_555_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_15_0_fu_98 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln226_fu_498_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_x_1_0_fu_102 <= add_ln225_fu_492_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln229_fu_509_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln232_fu_529_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln232_fu_529_p2 == 1'd1) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_1_0_fu_102 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln229_fu_509_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_y_1_0_fu_94 <= add_ln215_fu_429_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_1_0_fu_94 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln232_fu_529_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofm_x_1_0_fu_90 <= add_ln231_fu_523_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln232_fu_529_p2 == 1'd1) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_1_0_fu_90 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln232_fu_529_p2 == 1'd1) & (icmp_ln229_fu_509_p2 == 1'd1) & (icmp_ln226_fu_498_p2 == 1'd1) & (icmp_ln223_fu_481_p2 == 1'd1) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofm_y_1_0_fu_86 <= select_ln235_1_fu_563_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_0_fu_86 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln204_fu_350_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_1_0_fu_110 <= add_ln210_fu_772_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_1_0_fu_110 <= zext_ln251_fu_677_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_1_0_fu_110 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln214_fu_407_p2 == 1'd1) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln219_1_reg_908 <= add_ln219_1_fu_457_p2;
        add_ln220_reg_913 <= add_ln220_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln220_reg_913_pp0_iter1_reg <= add_ln220_reg_913;
        icmp_ln198_reg_900_pp0_iter1_reg <= icmp_ln198_reg_900;
        icmp_ln214_reg_904_pp0_iter1_reg <= icmp_ln214_reg_904;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln196_fu_376_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln198_reg_900 <= icmp_ln198_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln214_reg_904 <= icmp_ln214_fu_407_p2;
    end
end

always @ (*) begin
    if ((icmp_ln196_fu_376_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op154_read_state2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op111_read_state2 == 1'b1)))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_249)) begin
        if (((icmp_ln198_fu_398_p2 == 1'd1) & (trunc_ln321_fu_732_p1 == 2'd0))) begin
            inputBuf_0_V_address1 = zext_ln201_fu_724_p1;
        end else if ((1'b1 == ap_condition_694)) begin
            inputBuf_0_V_address1 = zext_ln247_fu_612_p1;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_249)) begin
        if (((icmp_ln198_fu_398_p2 == 1'd1) & (trunc_ln321_fu_732_p1 == 2'd1))) begin
            inputBuf_1_V_address1 = zext_ln201_fu_724_p1;
        end else if ((1'b1 == ap_condition_700)) begin
            inputBuf_1_V_address1 = zext_ln247_fu_612_p1;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_249)) begin
        if (((icmp_ln198_fu_398_p2 == 1'd1) & (trunc_ln321_fu_732_p1 == 2'd2))) begin
            inputBuf_2_V_address1 = zext_ln201_fu_724_p1;
        end else if ((1'b1 == ap_condition_704)) begin
            inputBuf_2_V_address1 = zext_ln247_fu_612_p1;
        end else begin
            inputBuf_2_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        inputBuf_2_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_2_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_2_V_we1 = 1'b1;
    end else begin
        inputBuf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_249)) begin
        if (((icmp_ln198_fu_398_p2 == 1'd1) & (trunc_ln321_fu_732_p1 == 2'd3))) begin
            inputBuf_3_V_address1 = zext_ln201_fu_724_p1;
        end else if ((1'b1 == ap_condition_708)) begin
            inputBuf_3_V_address1 = zext_ln247_fu_612_p1;
        end else begin
            inputBuf_3_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        inputBuf_3_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_3_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_3_V_we1 = 1'b1;
    end else begin
        inputBuf_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln214_reg_904_pp0_iter1_reg == 1'd1) & (icmp_ln198_reg_900_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_op206_write_state4 == 1'b1))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln196_fu_376_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln196_fu_376_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln196_fu_382_p2 = (i_0_0_reg_279 + 15'd1);

assign add_ln203_fu_736_p2 = (inp_15_0_fu_98 + 32'd1);

assign add_ln206_fu_752_p2 = (current_block_write_s_fu_114 + 32'd1);

assign add_ln210_fu_772_p2 = (read_block_1_0_fu_110 + 32'd1);

assign add_ln215_fu_429_p2 = (32'd1 + k_y_1_0_fu_94);

assign add_ln219_1_fu_457_p2 = (count_simd_1_0_fu_106 + sub_ln219_fu_451_p2);

assign add_ln219_fu_439_p2 = (ofm_x_1_0_fu_90 + k_x_1_0_fu_102);

assign add_ln220_1_fu_463_p2 = (2'd1 + trunc_ln215_1_fu_435_p1);

assign add_ln220_fu_469_p2 = (add_ln220_1_fu_463_p2 + trunc_ln215_fu_425_p1);

assign add_ln222_fu_475_p2 = (32'd1 + count_simd_1_0_fu_106);

assign add_ln225_fu_492_p2 = (k_x_1_0_fu_102 + 32'd1);

assign add_ln231_fu_523_p2 = (ofm_x_1_0_fu_90 + 32'd1);

assign add_ln234_fu_543_p2 = (ofm_y_1_0_fu_86 + 32'd1);

assign add_ln255_1_fu_627_p2 = (trunc_ln196_fu_394_p1 + 6'd1);

assign add_ln255_fu_633_p2 = (current_block_write_s_fu_114 + 32'd1);

assign add_ln262_fu_699_p2 = (counter_internal_blo_fu_122 + 32'd1);

assign and_ln244_fu_606_p2 = (icmp_ln244_fu_584_p2 & icmp_ln244_1_fu_600_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op154_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op111_read_state2 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op154_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op111_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op154_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op111_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op154_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op111_read_state2 == 1'b1)));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((out_V_V_TREADY == 1'b0) & (ap_predicate_op206_write_state4 == 1'b1));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_249 = ((icmp_ln196_fu_376_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_694 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd0));
end

always @ (*) begin
    ap_condition_700 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_704 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd2));
end

always @ (*) begin
    ap_condition_708 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd3));
end

always @ (*) begin
    ap_enable_operation_119 = (ap_predicate_op119_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_121 = (ap_predicate_op121_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_123 = (ap_predicate_op123_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_125 = (ap_predicate_op125_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_162 = (ap_predicate_op162_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_164 = (ap_predicate_op164_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_166 = (ap_predicate_op166_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_168 = (ap_predicate_op168_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_194 = (ap_predicate_op194_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_196 = (ap_predicate_op196_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_198 = (ap_predicate_op198_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_200 = (ap_predicate_op200_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_201 = (ap_predicate_op201_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_202 = (ap_predicate_op202_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_203 = (ap_predicate_op203_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_204 = (ap_predicate_op204_load_state4 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state2_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter1_stage0 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_enable_state4_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op111_read_state2 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op119_store_state2 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd2));
end

always @ (*) begin
    ap_predicate_op121_store_state2 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd1));
end

always @ (*) begin
    ap_predicate_op123_store_state2 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op125_store_state2 = ((1'd1 == and_ln244_fu_606_p2) & (icmp_ln198_fu_398_p2 == 1'd0) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_1_fu_620_p1 == 2'd3));
end

always @ (*) begin
    ap_predicate_op154_read_state2 = ((icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op162_store_state2 = ((icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd2));
end

always @ (*) begin
    ap_predicate_op164_store_state2 = ((icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd1));
end

always @ (*) begin
    ap_predicate_op166_store_state2 = ((icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op168_store_state2 = ((icmp_ln198_fu_398_p2 == 1'd1) & (icmp_ln196_fu_376_p2 == 1'd0) & (trunc_ln321_fu_732_p1 == 2'd3));
end

always @ (*) begin
    ap_predicate_op194_load_state3 = ((icmp_ln214_reg_904 == 1'd1) & (icmp_ln198_reg_900 == 1'd0));
end

always @ (*) begin
    ap_predicate_op196_load_state3 = ((icmp_ln214_reg_904 == 1'd1) & (icmp_ln198_reg_900 == 1'd0));
end

always @ (*) begin
    ap_predicate_op198_load_state3 = ((icmp_ln214_reg_904 == 1'd1) & (icmp_ln198_reg_900 == 1'd0));
end

always @ (*) begin
    ap_predicate_op200_load_state3 = ((icmp_ln214_reg_904 == 1'd1) & (icmp_ln198_reg_900 == 1'd0));
end

always @ (*) begin
    ap_predicate_op201_load_state4 = ((icmp_ln214_reg_904_pp0_iter1_reg == 1'd1) & (icmp_ln198_reg_900_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op202_load_state4 = ((icmp_ln214_reg_904_pp0_iter1_reg == 1'd1) & (icmp_ln198_reg_900_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op203_load_state4 = ((icmp_ln214_reg_904_pp0_iter1_reg == 1'd1) & (icmp_ln198_reg_900_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op204_load_state4 = ((icmp_ln214_reg_904_pp0_iter1_reg == 1'd1) & (icmp_ln198_reg_900_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op206_write_state4 = ((icmp_ln214_reg_904_pp0_iter1_reg == 1'd1) & (icmp_ln198_reg_900_pp0_iter1_reg == 1'd0));
end

assign grp_fu_338_p2 = (current_line_1_0_fu_118 + 32'd1);

assign icmp_ln196_fu_376_p2 = ((i_0_0_reg_279 == 15'd24588) ? 1'b1 : 1'b0);

assign icmp_ln198_fu_398_p2 = ((inp_15_0_fu_98 < 32'd288) ? 1'b1 : 1'b0);

assign icmp_ln204_fu_350_p2 = ((grp_fu_338_p2 == 32'd96) ? 1'b1 : 1'b0);

assign icmp_ln207_fu_758_p2 = ((add_ln206_fu_752_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_407_p2 = ((counter_internal_blo_fu_122 < 32'd809) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_481_p2 = ((add_ln222_fu_475_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln226_fu_498_p2 = ((add_ln225_fu_492_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln229_fu_509_p2 = ((add_ln215_fu_429_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln232_fu_529_p2 = ((add_ln231_fu_523_p2 == 32'd30) ? 1'b1 : 1'b0);

assign icmp_ln235_fu_549_p2 = ((add_ln234_fu_543_p2 == 32'd30) ? 1'b1 : 1'b0);

assign icmp_ln244_1_fu_600_p2 = ((tmp_1_fu_590_p4 == 27'd0) ? 1'b1 : 1'b0);

assign icmp_ln244_fu_584_p2 = ((counter_internal_blo_fu_122 < 32'd95) ? 1'b1 : 1'b0);

assign icmp_ln251_fu_344_p2 = ((grp_fu_338_p2 == 32'd96) ? 1'b1 : 1'b0);

assign icmp_ln256_fu_639_p2 = ((add_ln255_fu_633_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln263_fu_705_p2 = ((add_ln262_fu_699_p2 == 32'd809) ? 1'b1 : 1'b0);

assign inputBuf_0_V_address0 = zext_ln220_fu_788_p1;

assign inputBuf_1_V_address0 = zext_ln220_fu_788_p1;

assign inputBuf_2_V_address0 = zext_ln220_fu_788_p1;

assign inputBuf_3_V_address0 = zext_ln220_fu_788_p1;

assign out_V_V_TDATA = tmp_V_1_fu_795_p6;

assign select_ln207_fu_764_p3 = ((icmp_ln207_fu_758_p2[0:0] === 1'b1) ? 32'd0 : add_ln206_fu_752_p2);

assign select_ln235_1_fu_563_p3 = ((icmp_ln235_fu_549_p2[0:0] === 1'b1) ? 32'd0 : add_ln234_fu_543_p2);

assign select_ln235_fu_555_p3 = ((icmp_ln235_fu_549_p2[0:0] === 1'b1) ? 32'd0 : inp_15_0_fu_98);

assign select_ln251_1_fu_661_p3 = ((icmp_ln251_fu_344_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_338_p2);

assign select_ln251_2_fu_669_p3 = ((icmp_ln251_fu_344_p2[0:0] === 1'b1) ? add_ln255_1_fu_627_p2 : trunc_ln196_fu_394_p1);

assign select_ln251_fu_653_p3 = ((icmp_ln251_fu_344_p2[0:0] === 1'b1) ? select_ln256_fu_645_p3 : current_block_write_s_fu_114);

assign select_ln256_fu_645_p3 = ((icmp_ln256_fu_639_p2[0:0] === 1'b1) ? 32'd0 : add_ln255_fu_633_p2);

assign select_ln263_fu_711_p3 = ((icmp_ln263_fu_705_p2[0:0] === 1'b1) ? 32'd0 : add_ln262_fu_699_p2);

assign shl_ln219_fu_445_p2 = add_ln219_fu_439_p2 << 32'd2;

assign sub_ln219_fu_451_p2 = (shl_ln219_fu_445_p2 - add_ln219_fu_439_p2);

assign tmp_1_fu_590_p4 = {{read_block_1_0_fu_110[31:5]}};

assign trunc_ln196_fu_394_p1 = read_block_1_0_fu_110[5:0];

assign trunc_ln215_1_fu_435_p1 = current_block_write_s_fu_114[1:0];

assign trunc_ln215_fu_425_p1 = k_y_1_0_fu_94[1:0];

assign trunc_ln321_1_fu_620_p1 = current_block_write_s_fu_114[1:0];

assign trunc_ln321_fu_732_p1 = current_block_write_s_fu_114[1:0];

assign zext_ln201_fu_724_p1 = current_line_1_0_fu_118;

assign zext_ln220_fu_788_p1 = add_ln219_1_reg_908;

assign zext_ln247_fu_612_p1 = current_line_1_0_fu_118;

assign zext_ln251_fu_677_p1 = select_ln251_2_fu_669_p3;

endmodule //ConvolutionInputGenerator_0_ConvolutionInputGene_1
