# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0.xci
# IP: The module: 'top_rst_zynq_ps_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_zynq_ps_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_zynq_ps_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_zynq_ps_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0.xci
# IP: The module: 'top_rst_zynq_ps_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_zynq_ps_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_zynq_ps_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /workspace/Diplomski_rad/finn_modified_docker_output_dir/vivado_zynq_proj_cr8hg2w8/finn_zynq_link.srcs/sources_1/bd/top/ip/top_rst_zynq_ps_100M_0/top_rst_zynq_ps_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_zynq_ps_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
