-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ConvolutionInputGenerator_0_ConvolutionInputGene_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_V_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    in_V_V_TVALID : IN STD_LOGIC;
    in_V_V_TREADY : OUT STD_LOGIC;
    out_V_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_V_V_TVALID : OUT STD_LOGIC;
    out_V_V_TREADY : IN STD_LOGIC );
end;


architecture behav of ConvolutionInputGenerator_0_ConvolutionInputGene_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100000000";
    constant ap_const_lv16_EA00 : STD_LOGIC_VECTOR (15 downto 0) := "1110101000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_900 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000100100000000";
    constant ap_const_lv32_167F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001011001111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_2FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011111111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln197_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln199_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln245_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal icmp_ln199_reg_893 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln215_reg_897 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_0_reg_277 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_predicate_op119_read_state2 : BOOLEAN;
    signal ap_predicate_op162_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op205_write_state3 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln197_fu_380_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln215_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln221_fu_479_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln221_reg_901 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal inputBuf_0_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_0_V_ce0 : STD_LOGIC;
    signal inputBuf_0_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputBuf_0_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_0_V_ce1 : STD_LOGIC;
    signal inputBuf_0_V_we1 : STD_LOGIC;
    signal inputBuf_1_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_1_V_ce0 : STD_LOGIC;
    signal inputBuf_1_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputBuf_1_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_1_V_ce1 : STD_LOGIC;
    signal inputBuf_1_V_we1 : STD_LOGIC;
    signal inputBuf_2_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_2_V_ce0 : STD_LOGIC;
    signal inputBuf_2_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputBuf_2_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_2_V_ce1 : STD_LOGIC;
    signal inputBuf_2_V_we1 : STD_LOGIC;
    signal inputBuf_3_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_3_V_ce0 : STD_LOGIC;
    signal inputBuf_3_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal inputBuf_3_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal inputBuf_3_V_ce1 : STD_LOGIC;
    signal inputBuf_3_V_we1 : STD_LOGIC;
    signal zext_ln221_fu_465_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln248_fu_612_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln202_fu_724_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ofm_y_1_0_fu_84 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln236_1_fu_573_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln224_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln227_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln230_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln233_fu_539_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_x_1_0_fu_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln232_fu_533_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_1_0_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln216_fu_427_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_15_0_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln236_fu_565_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln204_fu_736_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_1_0_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln226_fu_502_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_1_0_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln223_fu_485_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_1_0_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln252_fu_677_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln211_fu_772_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln205_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_write_s_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln252_fu_653_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln208_fu_764_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_1_0_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln252_1_fu_661_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_blo_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln264_fu_711_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_1_fu_788_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln321_1_fu_620_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln321_fu_732_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln220_1_fu_441_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln220_fu_437_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln220_fu_445_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln_fu_451_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln220_1_fu_459_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln216_1_fu_433_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln221_1_fu_473_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln216_fu_423_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln235_fu_553_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln236_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln245_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln245_1_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln197_fu_392_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln256_fu_633_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln257_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln252_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln257_fu_645_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln256_1_fu_627_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln252_2_fu_669_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln263_fu_699_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln264_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln207_fu_752_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln208_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_predicate_op127_store_state2 : BOOLEAN;
    signal ap_enable_operation_127 : BOOLEAN;
    signal ap_enable_state2_pp0_iter0_stage0 : BOOLEAN;
    signal ap_predicate_op69_load_state2 : BOOLEAN;
    signal ap_enable_operation_69 : BOOLEAN;
    signal ap_predicate_op202_load_state3 : BOOLEAN;
    signal ap_enable_operation_202 : BOOLEAN;
    signal ap_enable_state3_pp0_iter1_stage0 : BOOLEAN;
    signal ap_predicate_op170_store_state2 : BOOLEAN;
    signal ap_enable_operation_170 : BOOLEAN;
    signal ap_predicate_op129_store_state2 : BOOLEAN;
    signal ap_enable_operation_129 : BOOLEAN;
    signal ap_predicate_op67_load_state2 : BOOLEAN;
    signal ap_enable_operation_67 : BOOLEAN;
    signal ap_predicate_op201_load_state3 : BOOLEAN;
    signal ap_enable_operation_201 : BOOLEAN;
    signal ap_predicate_op172_store_state2 : BOOLEAN;
    signal ap_enable_operation_172 : BOOLEAN;
    signal ap_predicate_op131_store_state2 : BOOLEAN;
    signal ap_enable_operation_131 : BOOLEAN;
    signal ap_predicate_op65_load_state2 : BOOLEAN;
    signal ap_enable_operation_65 : BOOLEAN;
    signal ap_predicate_op200_load_state3 : BOOLEAN;
    signal ap_enable_operation_200 : BOOLEAN;
    signal ap_predicate_op174_store_state2 : BOOLEAN;
    signal ap_enable_operation_174 : BOOLEAN;
    signal ap_predicate_op133_store_state2 : BOOLEAN;
    signal ap_enable_operation_133 : BOOLEAN;
    signal ap_predicate_op71_load_state2 : BOOLEAN;
    signal ap_enable_operation_71 : BOOLEAN;
    signal ap_predicate_op203_load_state3 : BOOLEAN;
    signal ap_enable_operation_203 : BOOLEAN;
    signal ap_predicate_op176_store_state2 : BOOLEAN;
    signal ap_enable_operation_176 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_660 : BOOLEAN;
    signal ap_condition_230 : BOOLEAN;
    signal ap_condition_666 : BOOLEAN;
    signal ap_condition_670 : BOOLEAN;
    signal ap_condition_674 : BOOLEAN;

    component ConvolutionInputGenerator_0_ConvolutionInputGfYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component ConvolutionInputGenerator_0_ConvolutionInputGbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    inputBuf_0_V_U : component ConvolutionInputGenerator_0_ConvolutionInputGbkb
    generic map (
        DataWidth => 8,
        AddressRange => 768,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_0_V_address0,
        ce0 => inputBuf_0_V_ce0,
        q0 => inputBuf_0_V_q0,
        address1 => inputBuf_0_V_address1,
        ce1 => inputBuf_0_V_ce1,
        we1 => inputBuf_0_V_we1,
        d1 => in_V_V_TDATA);

    inputBuf_1_V_U : component ConvolutionInputGenerator_0_ConvolutionInputGbkb
    generic map (
        DataWidth => 8,
        AddressRange => 768,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_V_address0,
        ce0 => inputBuf_1_V_ce0,
        q0 => inputBuf_1_V_q0,
        address1 => inputBuf_1_V_address1,
        ce1 => inputBuf_1_V_ce1,
        we1 => inputBuf_1_V_we1,
        d1 => in_V_V_TDATA);

    inputBuf_2_V_U : component ConvolutionInputGenerator_0_ConvolutionInputGbkb
    generic map (
        DataWidth => 8,
        AddressRange => 768,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_V_address0,
        ce0 => inputBuf_2_V_ce0,
        q0 => inputBuf_2_V_q0,
        address1 => inputBuf_2_V_address1,
        ce1 => inputBuf_2_V_ce1,
        we1 => inputBuf_2_V_we1,
        d1 => in_V_V_TDATA);

    inputBuf_3_V_U : component ConvolutionInputGenerator_0_ConvolutionInputGbkb
    generic map (
        DataWidth => 8,
        AddressRange => 768,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_V_address0,
        ce0 => inputBuf_3_V_ce0,
        q0 => inputBuf_3_V_q0,
        address1 => inputBuf_3_V_address1,
        ce1 => inputBuf_3_V_ce1,
        we1 => inputBuf_3_V_we1,
        d1 => in_V_V_TDATA);

    ConvolutionInputGfYi_U1 : component ConvolutionInputGenerator_0_ConvolutionInputGfYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => inputBuf_0_V_q0,
        din1 => inputBuf_1_V_q0,
        din2 => inputBuf_2_V_q0,
        din3 => inputBuf_3_V_q0,
        din4 => add_ln221_reg_901,
        dout => tmp_V_1_fu_788_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_simd_1_0_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln224_fu_491_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                count_simd_1_0_fu_104 <= add_ln223_fu_485_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln227_fu_508_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln230_fu_519_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln233_fu_539_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln233_fu_539_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                count_simd_1_0_fu_104 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    counter_internal_blo_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                counter_internal_blo_fu_120 <= select_ln264_fu_711_p3;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln205_fu_348_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                counter_internal_blo_fu_120 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_block_write_s_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln205_fu_348_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                current_block_write_s_fu_112 <= select_ln208_fu_764_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                current_block_write_s_fu_112 <= select_ln252_fu_653_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_block_write_s_fu_112 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_line_1_0_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln205_fu_348_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                current_line_1_0_fu_116 <= grp_fu_336_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                current_line_1_0_fu_116 <= select_ln252_1_fu_661_p3;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln205_fu_348_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                current_line_1_0_fu_116 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_0_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_0_reg_277 <= ap_const_lv16_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_0_0_reg_277 <= add_ln197_fu_380_p2;
            end if; 
        end if;
    end process;

    inp_15_0_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                inp_15_0_fu_96 <= add_ln204_fu_736_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln233_fu_539_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                inp_15_0_fu_96 <= select_ln236_fu_565_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                inp_15_0_fu_96 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_x_1_0_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln227_fu_508_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                k_x_1_0_fu_100 <= add_ln226_fu_502_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln230_fu_519_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln233_fu_539_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln233_fu_539_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_x_1_0_fu_100 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_y_1_0_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln230_fu_519_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                k_y_1_0_fu_92 <= add_ln216_fu_427_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_y_1_0_fu_92 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_x_1_0_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln233_fu_539_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ofm_x_1_0_fu_88 <= add_ln232_fu_533_p2;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln233_fu_539_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                ofm_x_1_0_fu_88 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_y_1_0_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln233_fu_539_p2 = ap_const_lv1_1) and (icmp_ln230_fu_519_p2 = ap_const_lv1_1) and (icmp_ln227_fu_508_p2 = ap_const_lv1_1) and (icmp_ln224_fu_491_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ofm_y_1_0_fu_84 <= select_ln236_1_fu_573_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ofm_y_1_0_fu_84 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    read_block_1_0_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln205_fu_348_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                read_block_1_0_fu_108 <= add_ln211_fu_772_p2;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                read_block_1_0_fu_108 <= zext_ln252_fu_677_p1;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                read_block_1_0_fu_108 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln221_reg_901 <= add_ln221_fu_479_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln199_reg_893 <= icmp_ln199_fu_396_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln215_reg_897 <= icmp_ln215_fu_405_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln197_fu_374_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln197_fu_374_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln197_fu_380_p2 <= std_logic_vector(unsigned(i_0_0_reg_277) + unsigned(ap_const_lv16_1));
    add_ln204_fu_736_p2 <= std_logic_vector(unsigned(inp_15_0_fu_96) + unsigned(ap_const_lv32_1));
    add_ln207_fu_752_p2 <= std_logic_vector(unsigned(current_block_write_s_fu_112) + unsigned(ap_const_lv32_1));
    add_ln211_fu_772_p2 <= std_logic_vector(unsigned(read_block_1_0_fu_108) + unsigned(ap_const_lv32_1));
    add_ln216_fu_427_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(k_y_1_0_fu_92));
    add_ln220_1_fu_459_p2 <= std_logic_vector(unsigned(shl_ln_fu_451_p3) + unsigned(count_simd_1_0_fu_104));
    add_ln220_fu_445_p2 <= std_logic_vector(unsigned(trunc_ln220_1_fu_441_p1) + unsigned(trunc_ln220_fu_437_p1));
    add_ln221_1_fu_473_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(trunc_ln216_1_fu_433_p1));
    add_ln221_fu_479_p2 <= std_logic_vector(unsigned(add_ln221_1_fu_473_p2) + unsigned(trunc_ln216_fu_423_p1));
    add_ln223_fu_485_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(count_simd_1_0_fu_104));
    add_ln226_fu_502_p2 <= std_logic_vector(unsigned(k_x_1_0_fu_100) + unsigned(ap_const_lv32_1));
    add_ln232_fu_533_p2 <= std_logic_vector(unsigned(ofm_x_1_0_fu_88) + unsigned(ap_const_lv32_1));
    add_ln235_fu_553_p2 <= std_logic_vector(unsigned(ofm_y_1_0_fu_84) + unsigned(ap_const_lv32_1));
    add_ln256_1_fu_627_p2 <= std_logic_vector(unsigned(trunc_ln197_fu_392_p1) + unsigned(ap_const_lv4_1));
    add_ln256_fu_633_p2 <= std_logic_vector(unsigned(current_block_write_s_fu_112) + unsigned(ap_const_lv32_1));
    add_ln263_fu_699_p2 <= std_logic_vector(unsigned(counter_internal_blo_fu_120) + unsigned(ap_const_lv32_1));
    and_ln245_fu_606_p2 <= (icmp_ln245_fu_594_p2 and icmp_ln245_1_fu_600_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_predicate_op119_read_state2, ap_predicate_op162_read_state2)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op162_read_state2 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op119_read_state2 = ap_const_boolean_1))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_predicate_op119_read_state2, ap_predicate_op162_read_state2, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op162_read_state2 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op119_read_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_V_V_TVALID, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_predicate_op119_read_state2, ap_predicate_op162_read_state2, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op162_read_state2 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op119_read_state2 = ap_const_boolean_1)))));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(in_V_V_TVALID, ap_predicate_op119_read_state2, ap_predicate_op162_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter0 <= (((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op162_read_state2 = ap_const_boolean_1)) or ((in_V_V_TVALID = ap_const_logic_0) and (ap_predicate_op119_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state3_io_assign_proc : process(out_V_V_TREADY, ap_predicate_op205_write_state3)
    begin
                ap_block_state3_io <= ((out_V_V_TREADY = ap_const_logic_0) and (ap_predicate_op205_write_state3 = ap_const_boolean_1));
    end process;

        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_230_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln197_fu_374_p2)
    begin
                ap_condition_230 <= ((icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_660_assign_proc : process(icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_condition_660 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_0));
    end process;


    ap_condition_666_assign_proc : process(icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_condition_666 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_1));
    end process;


    ap_condition_670_assign_proc : process(icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_condition_670 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_2));
    end process;


    ap_condition_674_assign_proc : process(icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_condition_674 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_3));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln197_fu_374_p2)
    begin
        if ((icmp_ln197_fu_374_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_operation_127_assign_proc : process(ap_predicate_op127_store_state2)
    begin
                ap_enable_operation_127 <= (ap_predicate_op127_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_129_assign_proc : process(ap_predicate_op129_store_state2)
    begin
                ap_enable_operation_129 <= (ap_predicate_op129_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_131_assign_proc : process(ap_predicate_op131_store_state2)
    begin
                ap_enable_operation_131 <= (ap_predicate_op131_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_133_assign_proc : process(ap_predicate_op133_store_state2)
    begin
                ap_enable_operation_133 <= (ap_predicate_op133_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_170_assign_proc : process(ap_predicate_op170_store_state2)
    begin
                ap_enable_operation_170 <= (ap_predicate_op170_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_172_assign_proc : process(ap_predicate_op172_store_state2)
    begin
                ap_enable_operation_172 <= (ap_predicate_op172_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_174_assign_proc : process(ap_predicate_op174_store_state2)
    begin
                ap_enable_operation_174 <= (ap_predicate_op174_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_176_assign_proc : process(ap_predicate_op176_store_state2)
    begin
                ap_enable_operation_176 <= (ap_predicate_op176_store_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_200_assign_proc : process(ap_predicate_op200_load_state3)
    begin
                ap_enable_operation_200 <= (ap_predicate_op200_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_201_assign_proc : process(ap_predicate_op201_load_state3)
    begin
                ap_enable_operation_201 <= (ap_predicate_op201_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_202_assign_proc : process(ap_predicate_op202_load_state3)
    begin
                ap_enable_operation_202 <= (ap_predicate_op202_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_203_assign_proc : process(ap_predicate_op203_load_state3)
    begin
                ap_enable_operation_203 <= (ap_predicate_op203_load_state3 = ap_const_boolean_1);
    end process;


    ap_enable_operation_65_assign_proc : process(ap_predicate_op65_load_state2)
    begin
                ap_enable_operation_65 <= (ap_predicate_op65_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_67_assign_proc : process(ap_predicate_op67_load_state2)
    begin
                ap_enable_operation_67 <= (ap_predicate_op67_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_69_assign_proc : process(ap_predicate_op69_load_state2)
    begin
                ap_enable_operation_69 <= (ap_predicate_op69_load_state2 = ap_const_boolean_1);
    end process;


    ap_enable_operation_71_assign_proc : process(ap_predicate_op71_load_state2)
    begin
                ap_enable_operation_71 <= (ap_predicate_op71_load_state2 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state2_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
                ap_enable_state2_pp0_iter0_stage0 <= ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state3_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state3_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op119_read_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2)
    begin
                ap_predicate_op119_read_state2 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op127_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_predicate_op127_store_state2 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_2));
    end process;


    ap_predicate_op129_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_predicate_op129_store_state2 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_1));
    end process;


    ap_predicate_op131_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_predicate_op131_store_state2 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_0));
    end process;


    ap_predicate_op133_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, trunc_ln321_1_fu_620_p1)
    begin
                ap_predicate_op133_store_state2 <= ((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_3));
    end process;


    ap_predicate_op162_read_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2)
    begin
                ap_predicate_op162_read_state2 <= ((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op170_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, trunc_ln321_fu_732_p1)
    begin
                ap_predicate_op170_store_state2 <= ((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_2));
    end process;


    ap_predicate_op172_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, trunc_ln321_fu_732_p1)
    begin
                ap_predicate_op172_store_state2 <= ((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_1));
    end process;


    ap_predicate_op174_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, trunc_ln321_fu_732_p1)
    begin
                ap_predicate_op174_store_state2 <= ((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_0));
    end process;


    ap_predicate_op176_store_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, trunc_ln321_fu_732_p1)
    begin
                ap_predicate_op176_store_state2 <= ((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_3));
    end process;


    ap_predicate_op200_load_state3_assign_proc : process(icmp_ln199_reg_893, icmp_ln215_reg_897)
    begin
                ap_predicate_op200_load_state3 <= ((icmp_ln215_reg_897 = ap_const_lv1_1) and (icmp_ln199_reg_893 = ap_const_lv1_0));
    end process;


    ap_predicate_op201_load_state3_assign_proc : process(icmp_ln199_reg_893, icmp_ln215_reg_897)
    begin
                ap_predicate_op201_load_state3 <= ((icmp_ln215_reg_897 = ap_const_lv1_1) and (icmp_ln199_reg_893 = ap_const_lv1_0));
    end process;


    ap_predicate_op202_load_state3_assign_proc : process(icmp_ln199_reg_893, icmp_ln215_reg_897)
    begin
                ap_predicate_op202_load_state3 <= ((icmp_ln215_reg_897 = ap_const_lv1_1) and (icmp_ln199_reg_893 = ap_const_lv1_0));
    end process;


    ap_predicate_op203_load_state3_assign_proc : process(icmp_ln199_reg_893, icmp_ln215_reg_897)
    begin
                ap_predicate_op203_load_state3 <= ((icmp_ln215_reg_897 = ap_const_lv1_1) and (icmp_ln199_reg_893 = ap_const_lv1_0));
    end process;


    ap_predicate_op205_write_state3_assign_proc : process(icmp_ln199_reg_893, icmp_ln215_reg_897)
    begin
                ap_predicate_op205_write_state3 <= ((icmp_ln215_reg_897 = ap_const_lv1_1) and (icmp_ln199_reg_893 = ap_const_lv1_0));
    end process;


    ap_predicate_op65_load_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, icmp_ln215_fu_405_p2)
    begin
                ap_predicate_op65_load_state2 <= ((icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op67_load_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, icmp_ln215_fu_405_p2)
    begin
                ap_predicate_op67_load_state2 <= ((icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op69_load_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, icmp_ln215_fu_405_p2)
    begin
                ap_predicate_op69_load_state2 <= ((icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op71_load_state2_assign_proc : process(icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, icmp_ln215_fu_405_p2)
    begin
                ap_predicate_op71_load_state2 <= ((icmp_ln215_fu_405_p2 = ap_const_lv1_1) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_336_p2 <= std_logic_vector(unsigned(current_line_1_0_fu_116) + unsigned(ap_const_lv32_1));
    icmp_ln197_fu_374_p2 <= "1" when (i_0_0_reg_277 = ap_const_lv16_EA00) else "0";
    icmp_ln199_fu_396_p2 <= "1" when (unsigned(inp_15_0_fu_96) < unsigned(ap_const_lv32_900)) else "0";
    icmp_ln205_fu_348_p2 <= "1" when (grp_fu_336_p2 = ap_const_lv32_300) else "0";
    icmp_ln208_fu_758_p2 <= "1" when (add_ln207_fu_752_p2 = ap_const_lv32_4) else "0";
    icmp_ln215_fu_405_p2 <= "1" when (unsigned(counter_internal_blo_fu_120) < unsigned(ap_const_lv32_167F)) else "0";
    icmp_ln224_fu_491_p2 <= "1" when (add_ln223_fu_485_p2 = ap_const_lv32_40) else "0";
    icmp_ln227_fu_508_p2 <= "1" when (add_ln226_fu_502_p2 = ap_const_lv32_3) else "0";
    icmp_ln230_fu_519_p2 <= "1" when (add_ln216_fu_427_p2 = ap_const_lv32_3) else "0";
    icmp_ln233_fu_539_p2 <= "1" when (add_ln232_fu_533_p2 = ap_const_lv32_A) else "0";
    icmp_ln236_fu_559_p2 <= "1" when (add_ln235_fu_553_p2 = ap_const_lv32_A) else "0";
    icmp_ln245_1_fu_600_p2 <= "1" when (unsigned(read_block_1_0_fu_108) < unsigned(ap_const_lv32_C)) else "0";
    icmp_ln245_fu_594_p2 <= "1" when (unsigned(counter_internal_blo_fu_120) < unsigned(ap_const_lv32_2FF)) else "0";
    icmp_ln252_fu_342_p2 <= "1" when (grp_fu_336_p2 = ap_const_lv32_300) else "0";
    icmp_ln257_fu_639_p2 <= "1" when (add_ln256_fu_633_p2 = ap_const_lv32_4) else "0";
    icmp_ln264_fu_705_p2 <= "1" when (add_ln263_fu_699_p2 = ap_const_lv32_167F) else "0";

    in_V_V_TDATA_blk_n_assign_proc : process(in_V_V_TVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2)
    begin
        if ((((ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            in_V_V_TDATA_blk_n <= in_V_V_TVALID;
        else 
            in_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_predicate_op119_read_state2, ap_predicate_op162_read_state2, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op162_read_state2 = ap_const_boolean_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op119_read_state2 = ap_const_boolean_1)))) then 
            in_V_V_TREADY <= ap_const_logic_1;
        else 
            in_V_V_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_0_V_address0 <= zext_ln221_fu_465_p1(10 - 1 downto 0);

    inputBuf_0_V_address1_assign_proc : process(icmp_ln199_fu_396_p2, zext_ln248_fu_612_p1, zext_ln202_fu_724_p1, trunc_ln321_fu_732_p1, ap_condition_660, ap_condition_230)
    begin
        if ((ap_const_boolean_1 = ap_condition_230)) then
            if (((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (trunc_ln321_fu_732_p1 = ap_const_lv2_0))) then 
                inputBuf_0_V_address1 <= zext_ln202_fu_724_p1(10 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_660)) then 
                inputBuf_0_V_address1 <= zext_ln248_fu_612_p1(10 - 1 downto 0);
            else 
                inputBuf_0_V_address1 <= "XXXXXXXXXX";
            end if;
        else 
            inputBuf_0_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    inputBuf_0_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inputBuf_0_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_0_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_0_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_1_V_address0 <= zext_ln221_fu_465_p1(10 - 1 downto 0);

    inputBuf_1_V_address1_assign_proc : process(icmp_ln199_fu_396_p2, zext_ln248_fu_612_p1, zext_ln202_fu_724_p1, trunc_ln321_fu_732_p1, ap_condition_230, ap_condition_666)
    begin
        if ((ap_const_boolean_1 = ap_condition_230)) then
            if (((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (trunc_ln321_fu_732_p1 = ap_const_lv2_1))) then 
                inputBuf_1_V_address1 <= zext_ln202_fu_724_p1(10 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_666)) then 
                inputBuf_1_V_address1 <= zext_ln248_fu_612_p1(10 - 1 downto 0);
            else 
                inputBuf_1_V_address1 <= "XXXXXXXXXX";
            end if;
        else 
            inputBuf_1_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    inputBuf_1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inputBuf_1_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_1_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_1_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_2_V_address0 <= zext_ln221_fu_465_p1(10 - 1 downto 0);

    inputBuf_2_V_address1_assign_proc : process(icmp_ln199_fu_396_p2, zext_ln248_fu_612_p1, zext_ln202_fu_724_p1, trunc_ln321_fu_732_p1, ap_condition_230, ap_condition_670)
    begin
        if ((ap_const_boolean_1 = ap_condition_230)) then
            if (((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (trunc_ln321_fu_732_p1 = ap_const_lv2_2))) then 
                inputBuf_2_V_address1 <= zext_ln202_fu_724_p1(10 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_670)) then 
                inputBuf_2_V_address1 <= zext_ln248_fu_612_p1(10 - 1 downto 0);
            else 
                inputBuf_2_V_address1 <= "XXXXXXXXXX";
            end if;
        else 
            inputBuf_2_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    inputBuf_2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inputBuf_2_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_2_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_2_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_3_V_address0 <= zext_ln221_fu_465_p1(10 - 1 downto 0);

    inputBuf_3_V_address1_assign_proc : process(icmp_ln199_fu_396_p2, zext_ln248_fu_612_p1, zext_ln202_fu_724_p1, trunc_ln321_fu_732_p1, ap_condition_230, ap_condition_674)
    begin
        if ((ap_const_boolean_1 = ap_condition_230)) then
            if (((icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (trunc_ln321_fu_732_p1 = ap_const_lv2_3))) then 
                inputBuf_3_V_address1 <= zext_ln202_fu_724_p1(10 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_674)) then 
                inputBuf_3_V_address1 <= zext_ln248_fu_612_p1(10 - 1 downto 0);
            else 
                inputBuf_3_V_address1 <= "XXXXXXXXXX";
            end if;
        else 
            inputBuf_3_V_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    inputBuf_3_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            inputBuf_3_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_3_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln197_fu_374_p2, icmp_ln199_fu_396_p2, and_ln245_fu_606_p2, ap_block_pp0_stage0_11001, trunc_ln321_1_fu_620_p1, trunc_ln321_fu_732_p1)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_lv1_1 = and_ln245_fu_606_p2) and (icmp_ln199_fu_396_p2 = ap_const_lv1_0) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_1_fu_620_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln199_fu_396_p2 = ap_const_lv1_1) and (icmp_ln197_fu_374_p2 = ap_const_lv1_0) and (trunc_ln321_fu_732_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            inputBuf_3_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    out_V_V_TDATA <= tmp_V_1_fu_788_p6;

    out_V_V_TDATA_blk_n_assign_proc : process(out_V_V_TREADY, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln199_reg_893, icmp_ln215_reg_897)
    begin
        if (((icmp_ln215_reg_897 = ap_const_lv1_1) and (icmp_ln199_reg_893 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_V_V_TDATA_blk_n <= out_V_V_TREADY;
        else 
            out_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_V_V_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op205_write_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op205_write_state3 = ap_const_boolean_1))) then 
            out_V_V_TVALID <= ap_const_logic_1;
        else 
            out_V_V_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln208_fu_764_p3 <= 
        ap_const_lv32_0 when (icmp_ln208_fu_758_p2(0) = '1') else 
        add_ln207_fu_752_p2;
    select_ln236_1_fu_573_p3 <= 
        ap_const_lv32_0 when (icmp_ln236_fu_559_p2(0) = '1') else 
        add_ln235_fu_553_p2;
    select_ln236_fu_565_p3 <= 
        ap_const_lv32_0 when (icmp_ln236_fu_559_p2(0) = '1') else 
        inp_15_0_fu_96;
    select_ln252_1_fu_661_p3 <= 
        ap_const_lv32_0 when (icmp_ln252_fu_342_p2(0) = '1') else 
        grp_fu_336_p2;
    select_ln252_2_fu_669_p3 <= 
        add_ln256_1_fu_627_p2 when (icmp_ln252_fu_342_p2(0) = '1') else 
        trunc_ln197_fu_392_p1;
    select_ln252_fu_653_p3 <= 
        select_ln257_fu_645_p3 when (icmp_ln252_fu_342_p2(0) = '1') else 
        current_block_write_s_fu_112;
    select_ln257_fu_645_p3 <= 
        ap_const_lv32_0 when (icmp_ln257_fu_639_p2(0) = '1') else 
        add_ln256_fu_633_p2;
    select_ln264_fu_711_p3 <= 
        ap_const_lv32_0 when (icmp_ln264_fu_705_p2(0) = '1') else 
        add_ln263_fu_699_p2;
    shl_ln_fu_451_p3 <= (add_ln220_fu_445_p2 & ap_const_lv6_0);
    trunc_ln197_fu_392_p1 <= read_block_1_0_fu_108(4 - 1 downto 0);
    trunc_ln216_1_fu_433_p1 <= current_block_write_s_fu_112(2 - 1 downto 0);
    trunc_ln216_fu_423_p1 <= k_y_1_0_fu_92(2 - 1 downto 0);
    trunc_ln220_1_fu_441_p1 <= ofm_x_1_0_fu_88(26 - 1 downto 0);
    trunc_ln220_fu_437_p1 <= k_x_1_0_fu_100(26 - 1 downto 0);
    trunc_ln321_1_fu_620_p1 <= current_block_write_s_fu_112(2 - 1 downto 0);
    trunc_ln321_fu_732_p1 <= current_block_write_s_fu_112(2 - 1 downto 0);
    zext_ln202_fu_724_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_1_0_fu_116),64));
    zext_ln221_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln220_1_fu_459_p2),64));
    zext_ln248_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_1_0_fu_116),64));
    zext_ln252_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln252_2_fu_669_p3),32));
end behav;
