# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj__xg6ldie/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_3/ip/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0.xci
# IP: The module: 'StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj__xg6ldie/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_3/ip/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0/constraints/StreamingDataflowPartition_3_IODMA_0_StreamingDataflowPartition_3_IODMA_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj__xg6ldie/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_3/ip/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0.xci
# IP: The module: 'StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/grgov/Diplomski_rad/finn_modified_docker_output_dir/vivado_stitch_proj__xg6ldie/finn_vivado_stitch_proj.srcs/sources_1/bd/StreamingDataflowPartition_3/ip/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0/constraints/StreamingDataflowPartition_3_IODMA_0_StreamingDataflowPartition_3_IODMA_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
