# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/StreamingDataflowPartition_3/StreamingDataflowPartition_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_3 || ORIG_REF_NAME==StreamingDataflowPartition_3} -quiet] -quiet

# IP: bd/StreamingDataflowPartition_3/ip/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0/StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0 || ORIG_REF_NAME==StreamingDataflowPartition_3_StreamingDataflowPartition_3_IODMA_0_0} -quiet] -quiet

# XDC: bd/StreamingDataflowPartition_3/StreamingDataflowPartition_3_ooc.xdc
